# Generated by Django 6.0.6 on 2026-06-24 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiring', '0009_vehiclehistory_driverhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='hiring.driver')),
            ],
            options={
                'verbose_name': 'Driver Auth Token',
                'verbose_name_plural': 'Driver Auth Tokens',
                'db_table': 'driver_auth_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('device', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hiring.driver')),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'db_table': 'driver_locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='hiring.driver')),
            ],
            options={
                'verbose_name': 'Driver OTP',
                'verbose_name_plural': 'Driver OTPs',
                'db_table': 'driver_otps',
                'ordering': ['-created_at'],
            },
        ),
    ]
