# Generated by Django 6.0.6 on 2026-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='start_working_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
