# Generated by Django 6.0.6 on 2026-06-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_start_working_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='start_working_date',
            new_name='started_working_date',
        ),
    ]
