# Generated by Django 6.0.6 on 2026-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_team_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contract_signer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_signer_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_template_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
