# Generated by Django 6.0.6 on 2026-08-15 15:02
#
# Seeds the real J&J Wasatch independent contractor agreement text onto the
# Wasatch Company row, tokenized with str.format() placeholders for the
# per-driver blanks. Matched by name (not a hardcoded id) so this is a safe
# no-op in any environment that doesn't have a Wasatch company row yet.

from django.db import migrations

CONTRACT_TEMPLATE_TEXT = """INDEPENDENT CONTRACTOR AGREEMENT
(NON-DOT LESS THAN 10,000 GVW)

THIS INDEPENDENT CONTRACTOR AGREEMENT (hereinafter the "Agreement"), is made and entered on this {effective_day} day of {effective_month}, {effective_year} (the "Effective Date"), by and between {company_name} located at {company_address} (the "Company") and, {contractor_name} with its principal place of business located at {contractor_address} (the "Contractor"). The Company and the Contractor are sometimes referred to in this Agreement collectively as the "Parties" and individually as "Party".

WHEREAS, Company is licensed by the Federal Motor Carrier Safety Administration ("FMCSA") as a property carrier;

WHEREAS, Contractor is in all respects qualified to transport freight in accordance with relevant state and federal laws and regulations;

WHEREAS, Company desires to engage Contractor on an independent contractor basis to provide freight transportation services pursuant to the provisions of this Agreement;

WHEREAS, Contractor is willing to be engaged by Company to transport freight on an independent contractor basis pursuant to the terms and subject to the conditions set forth in this Agreement;

WHEREAS, Contractor understands that Company would not provide Contractor this opportunity in the absence of this Agreement. To the extent that this Agreement replaces a prior agreement between Company and Contractor, Contractor understands that this Agreement supersedes any prior agreements and that Company would not provide Contractor with continued opportunity in the absence of this Agreement;

WHEREAS, Contractor had an opportunity to consult and present this Agreement to an attorney for review;

NOW THEREFORE, in consideration of the promises and agreements, and other good and valuable consideration, the receipt and adequacy of which are hereby acknowledged and intending to be legally bound, the Parties agree as follows:

I. SCOPE OF CONTRACTOR RELATIONSHIP

A. Contractor agrees and acknowledges that the transportation services provided by Contractor hereunder are to follow all Federal and State regulations, statutes, and other applicable laws. Such services shall include, but shall not be limited to, pickup, transportation, and drop-off of freight, expedited shipments, consisting of mandatory and time sensitive delivery schedules.

B. The Parties understand and agree that the Contractor is an independent contractor and not an employee of the Company. Nothing in this Agreement is intended to create or constitute an employment, joint venture, partnership, agency, trust or other relationship or association of any kind between the Parties. Contractor is expected to set its own hours, work using its own equipment and vehicle, carry its own insurance, accept or decline work on an individual job basis, get paid by the job, accept or decline work based on location preference, and is not prohibited from working for other similar companies. The Contractor will not be eligible to receive any employee benefits from Company and the Company is not responsible for providing Contractor or Contractor's employees with health insurance, unemployment compensation, social security, and workers compensation.

C. The Company will not make deductions from the Contractor's fees for taxes (except as otherwise required by applicable law or regulation). Any taxes imposed on the Contractor due to activities performed hereunder will be the sole responsibility of the Contractor. Except as otherwise provided herein, the Contractor is not an agent of Company and has no right, power or authority to obligate or bind the Company by contract or otherwise.

D. Company is not responsible for providing worker's compensation insurance for Contractor or any of Contractor's employees. Company is not responsible for providing any health or accident insurance to cover Contractor, or any of Contractor's drivers. Company is not responsible for providing any other contributions which might be expected in an employer-employee relationship. Contractor shall pay its own contributions to social security, unemployment insurance, federal or state withholding taxes. Contractor agrees to report and pay any necessary amounts for worker's compensation, taxes, unemployment insurance, social security, health insurance and other benefits for himself and his drivers.

E. Contractor shall be wholly responsible for all costs and expenses associated with transportation services provided to the Contractor, including gas expenses, tolls, tickets, damage as a result of accident, employee costs, costs and expenses of all Contractor's transportation equipment and maintenance, and the costs and expenses associated with the drivers who operate Contractor's vehicles.

F. Contractor hereby agrees to release, indemnify, defend, and hold harmless the Company (including reasonable costs, expenses and attorney's fees incurred by the Company) from any and all claims for unpaid taxes, workers compensation, social security benefits, unemployment compensation, health insurance claims, and/or arising from any and all injuries and accidents involving Contractor and Contractor's employees.

G. Contractor agrees that as to any work obtained through the Company, Contractor will not discriminate against any driver or applicant for employment by reason of race, creed, color, sex or national origin, or any protected group as defined by relevant federal and state law.

II. CONTRACTOR REQUIREMENTS:

A. Contractor, Contractor's drivers, and Contractor's other employees are not employees of Company.

B. Contractor must provide a certificate of insurance identifying "{company_name}" as additional insured with the following minimum requirements:
1) Must be an Accord form.
2) Commercial Auto Coverage: Trucking for Hire Operations.
3) $1,000,000 Primary Liability Commercial Auto CSL.
4) $100,000 Broad from Cargo with $1,000 deductible maximum.
5) Unlimited Radius of Operations (Full time with NO radius coverage restrictions). 200, 300 or 500-mile radius with a few runs outside this radius per year is NOT acceptable.
6) Certificate must also show listed Vehicles (Year, Make, VIN #) as well as all listed drivers.

C. Contractor and all of Contractor's drivers must be over the age of twenty-one (21).

D. Any driver(s) carrying a load for Company must be approved by Company prior to beginning work.

E. Contractor and any driver(s) carrying a load for Company must not have a DUI in the past 10 years.

F. Contractor and any driver(s) carrying a load for Company must have a valid driver license from the driver's state of residence.

G. Any driver(s) carrying a load for Company must have a minimum of 6 months of road driving experience for all cargo vans, sprinter vans and small straight box trucks (under 10,000 GVW).

H. Any driver(s) carrying a load for Company must own a nationwide coverage smartphone (IOS or Android) and know how to operate it.

I. Any driver(s) carrying a load for Company must own and know how to operate a GPS system.

III. VEHICLE REQUIREMENTS:

A. All vehicles must be year 2008 or newer.

B. All vehicles must be under 10,000 GVW.

C. All vehicles must be in good working order with up-to-date maintenance records.

D. Vehicles with paper plates are not accepted.

E. All vehicles must have "for hire" or "commercial" plates.

F. Temporary registrations will not be accepted.

G. All vehicles must have a minimum of 4 straps.

H. All unrelated decals must be removed from the vehicle unless the decals pertain to a company owned by Contractor or that operates under Contractor's authority.

I. Company must be notified immediately of any change in vehicle, prior to the vehicle being used by Contractor for providing services to Company. Company must receive new registration and insurance for any new vehicle prior to the vehicle being put on the road for Company or carrying any loads for Company.

IV. GENERAL OPERATING PROCEDURES:

A. Contractor will be paid for the distance travelled "from zip-code to zip-code." Contractor will not be paid based on the weight of the load carried; if Contractor has a weight limit for a specific vehicle, the Company should be notified prior to accepting a load. Company's dispatcher will agree to an amount with Contractor or Contractor's representative when a load is offered to Contractor. Any change in delivery location that exceeds twenty (20) miles will cause a recalculation of the payment due to Contractor. Any change in delivery location that does not exceed twenty (20) miles will NOT cause a recalculation of the payment due to Contractor; this is non-negotiable.

COMPANY IS UNDER NO OBLIGATION TO OFFER THE SAME RATE FOR THE SAME TRIP EVERY TIME. COMPANY RESERVES THE RIGHT TO SET THE PRICES THAT IT WILL PAY CONTRACTOR AT ITS SOLE DISCRETION AND CHANGE THOSE PRICES WITHOUT NOTICE. COMPANY'S RATE MAY CHANGE BASED ON ZIP CODE, GEOGRAPHIC REGION, DISTANCE, TIME OF DAY, DRIVERS IN A GEOGRAPHIC LOCATION, AND A VARIETY OF OTHER FACTORS.

B. All of Contractor's transportation prices and driver fees must be discussed when being offered a load, any agreement on a price is final. Including but not limited to:
1) Extra compensation for tolls.
2) Extra cents per mile due to the load exceeding Contractor's weight limit.
3) Short distance/long distance.

ALL CHANGES IN PRICE FOR TRANSPORTATION SERVICES ARE SET FORTH IN THE ORIENTATION DOCUMENT ATTACHED HERETO AS EXHIBIT "A". ONCE CONTRACTOR AGREES ON A PRICE AND PICKS UP A LOAD, ANY FURTHER NEGOTIATIONS INITIATED BY THE DRIVER OR CONTRACTOR ARE NULL AND VOID, EVEN IF AGREED TO BY THE COMPANY OR THE COMPANY'S DISPATCHER IN WRITING. THIS IS DONE TO PREVENT A CONTRACTOR OR A CONTRACTOR'S DRIVER FROM HOLDING A LOAD "HOSTAGE" TO RENEGOTIATE PRICE. IN THE EVENT THIS OCCURS, DISPATCHER WILL BE INSTRUCTED TO AGREE TO THE NEW PRICE BUT COMPANY WILL NOT MAKE THE NEW PAYMENT AMOUNT.

C. Contractor must check in with the Company at the main office number every morning on Monday through Saturday between 08:00 am and 09:30 am Eastern Standard Time:
1) Contractor must call Company's main office number to notify the Company whether it is available to accept loads and provide Contractor and/or its drivers' available location and availability for the day.
2) If Contractor is not available that day, Contractor must check in with Company and let the dispatcher know that Contractor and/or its drivers are not available.
3) If Contractor will not be working for a period of more than two days in a row, notify the dispatcher so that Contractor is excused from providing updates during that time.
4) If Contractor wishes to work on Sundays, call the Company's main office number to let the dispatcher know that Contractor is available to accept work.
5) If Contractor accepts a load from another company, it must notify Company's dispatcher that Contractor is out of service and how long Contractor will be out of service.
6) If Contractor changes its location from the original check-in, it must notify Company of its new location.

D. Once Contractor has placed itself in service, dispatchers will be looking for loads for Contractor. If dispatcher finds a load, he will call and offer it to Contractor. It is in Contractor's best interest to let the dispatcher know as fast as possible whether the load is accepted. If Contractor agrees to accept the load, Contractor is obligated to keep itself reserved and available for a minimum of fifteen to twenty (15-20) minutes so that Company may finalize the deal. If the load is awarded, Company's dispatcher will notify Contractor and provide pick-up and delivery information by text message. Contractor must call the main office or respond by text that the information is received.

E. Company will not pay more if extra pallets/skids can fit and are added at the shipping location. Contractor is paid based on distance, not based on weight. As long as the weight or volume fits in the vehicle, and does not cause the vehicle to be prohibitively overweight, Contractor must take the shipment. Failure to do so is a breach of this agreement and may result in Company terminating its relationship with Contractor.

F. Contractor and its drivers are restricted from discussing pricing with shippers or receivers. Any line of questioning to either, share the driver pay with shipper/receiver or to inquire how much this load was booked for, will result in immediate contract termination.

G. Contractor is prohibited from leaving personal belongings at a pickup or drop off location, and may not deposit trash into the dumpsters at those locations.

H. Contractor is prohibited from placing any personal belongings or objects on top of the pallets/boxes that are loaded into Contractor's vehicle.

I. Once Contractor has accepted a load from Company, it must provide a location update every two hours, additionally Contractor must:
1) Call upon arrival for pick up (as soon as Contractor arrives to the pickup location).
2) Call once loaded (number of pallets, total weight, BOL number).
3) Contractor may not leave the pickup location until the Company's dispatcher has been called, confirmed the pickup information, and gave Contractor permission to leave.
4) All freight must be strapped prior to leaving.
5) Call upon arrival for drop off (as soon as you arrive to the drop off location).
6) Call once dropped off with Proof of Delivery ("POD") (first and last name of the person who signed for the freight).
7) If Contractor is running late, Contractor must notify Company's dispatcher as soon as it becomes possible that Contractor will be late, NOT WHEN CONTRACTOR IS ALREADY RUNNING LATE.
8) ANY FAILURE TO PICK UP OR DELIVER A LOAD AS AGREED WILL RESULT IN A REDUCTION IN FEE DUE TO THE CONTRACTOR AND/OR TERMINATION OF THIS AGREEMENT. All reduction and detention fees are specified in Exhibit A hereto.

J. Company's dispatcher must be notified of all cancellations and transportation/location change requests:
1) Contractor's delivery time is set by Company's DISPATCHER, not the shipping company.
2) If a shipper states that a load is cancelled, Contractor is to call the dispatcher and confirm that the load is cancelled before leaving.
3) If the shipper requests that a load be unloaded in a different location than previously agreed, Contractor must call the dispatcher to confirm the location before moving.
4) Contractor must obtain permission from the dispatcher to pick-up or deliver a load earlier than scheduled. Failure to do so may result in charges to the Contractor.

K. Loading and Unloading freight:
1) If the shipper requests that Contractor assist in loading or unloading freight, Contractor must obtain approval from the dispatcher before starting. In order for Contractor to be paid for the labor, dispatcher must approve the work prior to starting.
2) If Contractor loads or unloads freight without the dispatcher's approval, it will not be paid for the labor.

V. RECOVERY POLICY:

A. If Contractor's vehicle breaks down while carrying a Company load, Contractor must immediately notify the dispatcher so that the dispatcher can find another vehicle to pick-up and deliver the load to its destination.

B. Contractor shall provide Company with the repair receipt and/or other document evidencing the breakdown within 48 hours of the incident. Failure to do so will result in penalties to the Contractor up to 100% of the total amount of the shipment payment.

C. Compensation:
1) The driver who makes the recovery shall be paid the amount necessary to deliver the load from the breakdown site to its destination.
2) The amount due to the driver will be deducted from the rate for the whole trip and Contractor shall be paid the remainder regardless of the distance that Contractor travelled prior to breaking down.
3) Other incidental charges will be covered only as agreed with the Company and only after the Contractor provides evidence and/or receipts of the charges.

VI. PAYMENT:

A. All Bills of Lading ("BOL") must be emailed to Company's dispatch address via Cam Scan mobile application or equivalent IMMEDIATELY AFTER DELIVERY OR AS SOON AS POSSIBLE THEREAFTER.

B. BOLs MUST BE IN PDF FORMAT ONLY. Poorly scanned BOLs shall not be processed for payment. Contractor must specify the TRUCK # and a PRO NUMBER on BOLs and include the TRUCK # in the email subject line.

C. Company will make payment to Contractor within seven (7) days of receipt of the original BOL.

D. To receive a PAYMENT REPORT by e-mail, list Contractor's primary email address below: {contractor_email}.

VII. CLAIMS, LIABILITY LIMITATION, DEDUCTIONS:

A. Contractor shall notify Company immediately upon learning of overages, shortages, or damaged freight that was handled by Contractor. Contractor shall return all overages. Disposition of damaged goods will be determined solely by Company.

B. Contractor acknowledges and agrees that it will not drop any freight other than at the designated business facilities of consignee or at a location designated by Company. Contractor further agrees that, in the event any loss of or damage to the cargo occurs as a result of Contractor's breach of this provision, Contractor will indemnify and hold Company and its customers harmless for any such loss or damage, including reasonable court costs and attorneys' fees.

C. In the event of loss, damage or delay in delivery, Contractor shall be liable for damage arising from any breach of the provisions of this section. The loss, damage, or injury shall be measured as the lesser of the actual replacement cost or the cost of repair, subject to a maximum of $1 million ($US) per shipment, less the reasonable salvage value of the damaged freight.

D. Contractor shall indemnify Company for all indirect, special or consequential damages, or other special economic losses, including attorney fees that might be recovered against Company as a result of a claim against Company arising from Contractor's conduct or transportation services. Contractor shall promptly pay Company all claim amounts due hereunder and further authorizes Company to deduct all such amounts from any amounts owed or due to the Contractor from the Company.

E. In addition, Contractor shall be solely liable and responsible for any claim arising from any reckless, dishonest or illegal acts of Contractor or Contractor's employee or agent and any claim arising from Contractor's furnishing contaminated and/or deficient vehicles or equipment.

VIII. MISCELLANEOUS:

A. Binding Effect. Each of the signatories below hereby represents and warrants that he or she has necessary authority to bind any Party on whose behalf they are signing. This Agreement shall inure to the benefit of and be binding upon the Parties and their subsidiary and affiliated companies, owners, shareholders, directors, partners, officers, agents, contractors, insurers, consultants, predecessors, successors, assigns, and employees, past and present.

B. Governing Law and Forum Choice. This Agreement shall be governed by and construed in accordance with the laws of the Commonwealth of Pennsylvania, without regard to its principles and conflicts of law. The Parties consent to the jurisdiction of the state or federal courts in Philadelphia County, Pennsylvania, with respect to any claim that may arise in the future from or in connection with this Agreement or the Parties' business relationship.

C. Integration, Modification and Interpretation. This Agreement constitutes the sole and complete record of the agreement of the Parties hereto with respect to the matters covered herein and supersedes and replaces all prior negotiations and agreements, proposed or otherwise, whether written or oral, concerning the subject matters herein. This Agreement may not be modified except in writing signed by all of the Parties.

D. Severability. Should any provision of this Agreement be declared illegal or unenforceable by any court of competent jurisdiction and cannot be modified to be enforceable, including the general release language, such provision shall immediately become null and void, leaving the remainder of this Agreement in full force and effect. Notwithstanding any of the foregoing, if any such provision determined to be invalid, illegal or unenforceable may be made valid, legal or enforceable by modification thereof, then the Party for whose benefit the provision exists may make such modification as may be necessary to make such provision valid, legal or enforceable.

E. Construction. The headings and captions of this Agreement are provided for convenience only and are intended to have no effect in construing or interpreting this Agreement. The language in all parts of this Agreement shall be in all cases construed as chosen by the Parties hereto to express their mutual intent, and shall be interpreted according to its fair meaning and not strictly for or against the Company or Contractor.

F. Counterparts. This Agreement may be executed in separate counterparts, each of which is deemed to be an original and all of which taken together constitute one and the same agreement.

G. Termination. This Agreement may be terminated by either Party upon written notice to be delivered by regular mail, email, or hand delivery to the other Party's above listed address or email address. After termination, the Parties shall calculate any amounts owed and due to the other Party and make payment in full for those amounts within thirty (30) days of terminating this Agreement.

H. No Waiver. No failure or neglect of either Party hereto in any instance to exercise any right, power or privilege hereunder or under law shall constitute a waiver of any other right, power or privilege or of the same right, power or privilege in any other instance. All waivers by either party hereto shall be contained in a written instrument signed by the Party to be charged.

I. Notices. Any notice, request, consent or approval required or permitted to be given under this Agreement or pursuant to law shall be sufficient if in writing, and if and when sent by certified mail to the Company's principal office as set forth above or Contractor's address as set forth above.

IX. VOLUNTARY EXECUTION OF AGREEMENT:

THE PARTIES STIPULATE THAT THEY HAVE HAD THE OPPORTUNITY TO CONSULT WITH COUNSEL OF THEIR OWN CHOOSING IN THE NEGOTIATION AND PREPARATION OF THIS AGREEMENT; AND THAT THEY HAVE READ THIS AGREEMENT AND HAVE HAD THE OPPORTUNITY TO HAVE ITS CONTENTS AND EFFECT FULLY EXPLAINED TO THEM BY SUCH COUNSEL AND ARE FULLY AWARE OF AND UNDERSTAND ALL OF ITS TERMS AND THE LEGAL CONSEQUENCES THEREOF. IT IS ACKNOWLEDGED THAT THE PARTIES TO THIS AGREEMENT HAVE MUTUALLY PARTICIPATED IN THE PREPARATION OF THIS AGREEMENT AND IT IS AGREED THAT NO PROVISION IN THIS AGREEMENT SHALL BE CONSTRUED AGAINST ANY PARTY BY VIRTUE OF THE ACTIONS OF THAT PARTY AND/OR ITS COUNSEL.

IN WITNESS WHEREOF, the Parties have duly executed this Agreement as of the date first set forth below and agree to the terms in the orientation packet attached hereto as Exhibit "A" which is an integral part of this Agreement and is incorporated by reference."""


def seed_wasatch_contract_template(apps, schema_editor):
    Company = apps.get_model('users', 'Company')
    Company.objects.filter(name__icontains='wasatch').update(
        contract_template_text=CONTRACT_TEMPLATE_TEXT,
        contract_signer_name='John Fenianos',
        contract_signer_title='Owner',
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_contract_signer_name_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_wasatch_contract_template, noop_reverse),
    ]
