# Generated by Django 4.2 on 2026-03-28 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('hiring', '0002_driver_telegram_group_id'),
        ('users', '0002_company_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('final', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payroll/statement/')),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('telegram_send', models.DateTimeField(blank=True, null=True)),
                ('email_send', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiring.driver')),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
                'db_table': 'statements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StatementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Statement Status',
                'verbose_name_plural': 'Statement Statuses',
                'db_table': 'statement_statuses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StatementLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.statement')),
            ],
            options={
                'verbose_name': 'Statement Load',
                'verbose_name_plural': 'Statement Loads',
                'db_table': 'statement_loads',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='statement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.statementstatus'),
        ),
    ]
