# Generated by Django 4.2 on 2026-04-02 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_deductiontype_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.statement')),
            ],
            options={
                'verbose_name': 'Statement Deduction',
                'verbose_name_plural': 'Statement Deductions',
                'db_table': 'statement_deductions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
            ],
            options={
                'verbose_name': 'Deduction History',
                'verbose_name_plural': 'Deduction Histories',
                'db_table': 'deduction_histories',
            },
        ),
    ]
