# Generated by Django 4.2 on 2026-03-28 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_company_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiring', '0002_driver_telegram_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mc', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ai_type', models.CharField(default='GPT', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'db_table': 'brokers',
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.IntegerField(blank=True, null=True)),
                ('load_number', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('carrier_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('drop_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('loaded_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('empty_miles', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('recovery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.broker')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring.driver')),
                ('main_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.load')),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
                'db_table': 'loads',
            },
        ),
        migrations.CreateModel(
            name='LoadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Load Status',
                'verbose_name_plural': 'Load Statuses',
                'db_table': 'load_statuses',
            },
        ),
        migrations.CreateModel(
            name='LoadStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField()),
                ('trailer_pickup', models.BooleanField(default=False)),
                ('trailer_drop', models.BooleanField(default=False)),
                ('last_location', models.BooleanField(default=False)),
                ('partial', models.BooleanField(default=False)),
                ('load_pickup', models.BooleanField(default=False)),
                ('load_drop', models.BooleanField(default=False)),
                ('trailer_info', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
            ],
            options={
                'verbose_name': 'Load Stop',
                'verbose_name_plural': 'Load Stops',
                'db_table': 'load_stops',
            },
        ),
        migrations.CreateModel(
            name='LoadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
            ],
            options={
                'verbose_name': 'Load History',
                'verbose_name_plural': 'Load Histories',
                'db_table': 'load_history',
            },
        ),
        migrations.CreateModel(
            name='LoadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='billing/loads/')),
                ('rc_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
            ],
            options={
                'verbose_name': 'Load File',
                'verbose_name_plural': 'Load Files',
                'db_table': 'load_files',
            },
        ),
        migrations.AddField(
            model_name='load',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.loadstatus'),
        ),
        migrations.CreateModel(
            name='BatchLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
            ],
            options={
                'verbose_name': 'Batch Load',
                'verbose_name_plural': 'Batch Loads',
                'db_table': 'batch_loads',
            },
        ),
    ]
