# Generated by Django 4.2 on 2026-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
