# Generated by Django 4.2 on 2026-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_load_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
