# Generated by Django 4.2 on 2026-04-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_load_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='LoadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.load')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.tag')),
            ],
            options={
                'verbose_name': 'Load Tag',
                'verbose_name_plural': 'Load Tags',
                'db_table': 'load_tags',
            },
        ),
    ]
