# Generated by Django 4.2 on 2026-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_tag_loadtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='dispatcher_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
