# Generated by Django 4.2 on 2026-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_load_dispatcher_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
