# Generated by Django 6.0.6 on 2026-08-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_brokerstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='broker',
            name='mc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BrokerStar',
        ),
    ]
