# Generated by Django 6.0.6 on 2026-09-03 15:31

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_broker_comment_broker_star_alter_broker_mc_and_more'),
        ('users', '0012_seed_wasatch_contract_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mc', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_blacklist', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker Blacklist Entry',
                'verbose_name_plural': 'Broker Blacklist',
                'db_table': 'broker_blacklist',
                'indexes': [models.Index(fields=['company', 'mc'], name='broker_blacklist_co_mc_idx'), models.Index(fields=['company'], name='broker_blacklist_co_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mc', ''), _negated=True), fields=('company', 'mc'), name='broker_blacklist_unique_company_mc'), models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('name'), condition=models.Q(('mc', '')), name='broker_blacklist_unique_company_name'), models.CheckConstraint(condition=models.Q(('mc', ''), ('name', ''), _negated=True), name='broker_blacklist_needs_mc_or_name')],
            },
        ),
    ]
