# Generated by Django 4.2 on 2026-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='telegram_group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
