# Generated by Django 4.2 on 2026-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_driver_cdl_class_driver_cdl_endorsement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='unit_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
