# Generated by Django 4.2 on 2026-06-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_driverinvitelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfile',
            options={'verbose_name': 'Company File', 'verbose_name_plural': 'Company Files'},
        ),
        migrations.AlterModelOptions(
            name='driverfile',
            options={'verbose_name': 'Driver File', 'verbose_name_plural': 'Driver Files'},
        ),
        migrations.AlterModelOptions(
            name='vehiclefile',
            options={'verbose_name': 'Vehicle File', 'verbose_name_plural': 'Vehicle Files'},
        ),
        migrations.AlterModelTable(
            name='companyfile',
            table='company_files',
        ),
        migrations.AlterModelTable(
            name='driverfile',
            table='driver_files',
        ),
        migrations.AlterModelTable(
            name='vehiclefile',
            table='vehicle_files',
        ),
    ]
