# Generated by Django 6.0.6 on 2026-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0009_vehiclehistory_driverhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
