# Generated by Django 6.0.6 on 2026-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0010_driver_current_address_driver_current_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
