# Generated by Django 6.0.6 on 2026-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0011_vehicle_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
