# Generated by Django 6.0.6 on 2026-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0012_driver_current_latitude_driver_current_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
