# Generated by Django 6.0.6 on 2026-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0015_deposit_deposithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fatca_reporting_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='payee_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='dock_height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
