# Generated by Django 6.0.6 on 2026-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0017_drivercompany_applicant_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
