# Generated by Django 6.0.6 on 2026-09-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0020_driverinvitelink_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='hiring.drivercompany'),
        ),
    ]
