# Generated by Django 6.0.6 on 2026-09-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0022_backfill_driver_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivercompany',
            name='driver',
        ),
    ]
